market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import LoginView, RegisterView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('products/', include('products.urls', namespace='products')),
    path('', RedirectView.as_view(url='/products/')),

]

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailView

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<slug>', ProductDetailView.as_view(), name='detail'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, username, full_name, email, password, phone_number=None, is_staff=False, is_admin=False):
        if not username:
            raise ValueError("User must have an username.")
        if not password:
            raise ValueError("User must have a password.")

        user_obj = self.model(
            username=username,
            full_name=full_name,
            email=self.normalize_email(email),
            phone_number=phone_number
        )
        user_obj.set_password(password)
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, username, full_name, email, password, phone_number=None):
        user = self.create_user(username, full_name, email, password, phone_number=phone_number, is_staff=True)
        return user

    def create_superuser(self, username, full_name, email, password, phone_number=None):
        user = self.create_user(username, full_name, email, password, phone_number=phone_number, is_staff=True, is_admin=True)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(max_length=120, unique=True)
    phone_number = models.CharField(max_length=120, blank=True, null=True)
    username = models.CharField(max_length=120, unique=True)
    full_name = models.CharField(max_length=120)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'full_name']    # Username field and password are required by default

    objects = UserManager()

    def __str__(self):
        return self.username

    def get_full_name(self):
        return self.full_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

products/models.py
from django.db import models
import os
import random
from market.utils import unique_slug_generator
from django.db.models.signals import pre_save
from django.urls import reverse


# Create your models here.
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1, 3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "products/{new_filename}/{final_filename}".format(
            new_filename=new_filename,
            final_filename=final_filename
    )


class Products(models.Model):
    name = models.CharField(max_length=120)
    slug = models.SlugField(blank=True, null=True)
    quantity = models.IntegerField(default=0)
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:detail", kwargs={'slug': self.slug})


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_receiver, sender=Products)

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
User = get_user_model()


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        request = self.request
        data = self.cleaned_data
        username = data.get("username")
        password = data.get("password")

        user = authenticate(request, username=username, password=password)
        if user is None:
            raise forms.ValidationError("Invalid credentials")
        login(request, user)
        return data


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'full_name', 'email', 'phone_number')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name', 'username',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('full_name', 'username', 'password', 'admin')

    def clean_password(self):
        return self.initial["password"]

accounts/views.py
from django.views.generic import CreateView, FormView

from .forms import LoginForm, RegisterForm
from market.mixins import RequestFormAttachMixin


# Create your views here.
class LoginView(RequestFormAttachMixin, FormView):
    form_class = LoginForm
    template_name = 'accounts/login.html'
    success_url = '/'
    default_next = '/'


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/'

products/views.py
from django.views.generic import ListView, DetailView
from .models import Products
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class ProductListView(LoginRequiredMixin, ListView):
    template_name = 'products/list.html'

    def get_queryset(self):
        return Products.objects.all()


class ProductDetailView(LoginRequiredMixin, DetailView):
    template_name = 'products/detail.html'

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        instance = get_object_or_404(Products, slug=slug)
        return instance

accounts/templates/accounts/login.html
{% extends 'products/base.html' %}

{% block content %}
{% include 'accounts/login_form.html' with form=form %}
{% endblock %}

accounts/templates/accounts/login_form.html
<form method="POST" action="{% if action_url %}{{ action_url }}{% else %}{% url 'login' %}{% endif %}" class="my-3"> {% csrf_token %}
    {% if next_url %}
        <input type="hidden" name="next" value="{{ next_url }}">
    {% endif %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Submit</button>
</form>

accounts/templates/accounts/register.html
{% extends 'products/base.html' %}

{% block content %}
<form method="POST" class="my-3"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Submit</button>
</form>
{% endblock %}

products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Products</title>
  </head>
  <body>

  {% include 'products/navbar.html' with brand_name='Market' %}

    <div class="container">
      {% block content %}
        <h1>Welcome to Market!</h1>
      {% endblock %}
    </div>

    {% include 'products/js.html' %}
  </body>
</html>

products/templates/products/card_products.html
{% block view %}
<div class="card rounded my-1" style="width: 18rem;">
  <div class="card-body rounded">
    <h5 class="card-title">{{ instance.name }}</h5>
    <a href="{{ instance.get_absolute_url }}" class="btn btn-primary">View</a>
  </div>
</div>
{% endblock %}

products/templates/products/detail.html
{% extends 'products/base.html' %}

{% block content %}
    <br><br>
    <div class="row ml-4">
        <div class="col-12 col-md-6">
            <h3>{{ object.name }} </h3><br>
            Only {{ object.quantity }} left in stock. HURRY!!!<br>
        </div>

        <div class="col-12 col-md-6">
            {% if object.image %}
                <img src='{{ object.image.url }}' class='img-fluid h-75 max-width:10%;' />
            {% endif %}
        </div>
    </div>

{% endblock %}

products/templates/products/js.html
{% load static %}

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


<script src="https://kit.fontawesome.com/24ec8c1e31.js" crossorigin="anonymous"></script>

<!-- js Render -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.88/jsrender.min.js'></script>

products/templates/products/list.html
{% extends 'products/base.html' %}

{% block content %}
<div class="container">
    <div class="row my-2">
        {% for obj in object_list %}
            <div class="col">
                {% include 'products/card_products.html' with instance=obj %}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

products/templates/products/navbar.html
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'products:list' as products_url %}
{% url 'register' as register_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <a class="navbar-brand" href="#">Market</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == products_url %}active{% endif %}">
        <a class="nav-link" href="{{ products_url }}">Products</a>
      </li>
        </a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle {% if request.path == account_url %}active{% endif %}" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <div class="dropdown-divider"></div>
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </div>
      </li>

      {% else %}
        <li class="nav-item {% if request.path == login_url %}active{% endif %}">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item {% if request.path == register_url %}active{% endif %}">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>